version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./Celery_Downloader
    ports:
      - "8000:8000"
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./Celery_Downloader
    volumes:
      - ./Celery_Downloader/src/cats:/app/src/cats
    command: ['celery', '--workdir=./src', '-A', 'src', 'worker']

